In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'col1': [1, 2, 3]})
df

col1
0     1
1     2
2     3

### The column of a dataframe is a Pandas Series:

In [5]:
print(f'Type of column of dataframe: {type(df.iloc[0])}')

Type of column of dataframe: <class 'pandas.core.series.Series'>


In [69]:
print(f'Type of column of dataframe: {type(df["col1"])}')

Type of column of dataframe: <class 'pandas.core.series.Series'>


### When a single-column dataframe is squeezed, you get a Pandas Series:

In [14]:
print(type(df.squeeze()))

<class 'pandas.core.series.Series'>


In [10]:
df.squeeze()

0    1
1    2
2    3
Name: col1, dtype: int64

### You cannot squeeze a multi-column dataframe into a series:

In [11]:
df2 = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})
df2

col1  col2
0     1     4
1     2     5
2     3     6

In [15]:
print(type(df2.squeeze()))

<class 'pandas.core.frame.DataFrame'>


### Dataframe.to_numpy() gives Numpy array (available since Pandas v0.24):

In [19]:
df2.to_numpy()

array([[1, 4],
       [2, 5],
       [3, 6]])

### ... but the dtype becomes the one which can fit all values.
### If there are objects, dtype becomes object for all values:

In [41]:
df2['col3'] = pd.date_range(2000, periods=3)
df2

col1  col2                       col3
0     1     4 1970-01-01 00:00:00.000002
1     2     5 1970-01-02 00:00:00.000002
2     3     6 1970-01-03 00:00:00.000002

In [42]:
df2.to_numpy()

array([[1, 4, Timestamp('1970-01-01 00:00:00.000002')],
       [2, 5, Timestamp('1970-01-02 00:00:00.000002')],
       [3, 6, Timestamp('1970-01-03 00:00:00.000002')]], dtype=object)

### Creating numpy arrays with keys and values using records:

In [71]:
records = np.rec.fromarrays((np.array(['a', 'b', 'c']),
                             np.arange(3),
                             np.arange(4,7)),
                            names=['keys', 'values', 'more values']) # , dtype=['U1', 'f8'])
records

rec.array([('a', 0, 4), ('b', 1, 5), ('c', 2, 6)],
          dtype=[('keys', '<U1'), ('values', '<i8'), ('more values', '<i8')])

In [72]:
records['keys']

array(['a', 'b', 'c'], dtype='<U1')

In [73]:
records['values']

array([0, 1, 2])

In [74]:
records['more values']

array([4, 5, 6])

In [75]:
pd.DataFrame(records)

keys  values  more values
0    a       0            4
1    b       1            5
2    c       2            6

### Creating numpy arrays with specific dtypes:

In [77]:
records = np.rec.fromarrays((np.array(['a', 'b', 'c']),
                             np.arange(3),
                             np.arange(4,7)),
                            dtype='U1, f8, i4')
records

rec.array([('a', 0., 4), ('b', 1., 5), ('c', 2., 6)],
          dtype=[('f0', '<U1'), ('f1', '<f8'), ('f2', '<i4')])

### ... haven't found a way to create a records array with dtype and names both specified.