In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(data={'col1': [1, 2, 3], 'col2': [4, 5, 6]})
df

col1  col2
0     1     4
1     2     5
2     3     6

## Convert DataFrame to Numpy array, and then flatten:

In [4]:
arr = df.to_numpy()
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

### Flatten using array.flatten():

In [5]:
arr.flatten()

array([1, 4, 2, 5, 3, 6])

### Flatten using array.reshape(-1):

In [6]:
arr.reshape(-1)

array([1, 4, 2, 5, 3, 6])

### Flatten using np.ravel(arr)

In [7]:
np.ravel(arr)     # Default row-major order or C-style order

array([1, 4, 2, 5, 3, 6])

In [8]:
np.ravel(arr, order='C')  # Explicit row-major order or C-style order

array([1, 4, 2, 5, 3, 6])

In [9]:
np.ravel(arr, order='F')  # Explicit column-major order or Fortran-style order

array([1, 2, 3, 4, 5, 6])