In [1]:
import os
import tensorflow as tf
import cProfile

In [2]:
tf.executing_eagerly()  # In TF2 eager execution is enabled by default

True

#### Tensors
  - Shape of a tensor are the number of elements in each dimension (ex. 2 rows, 3 columns -> TensorShape([2, 3]))
  - Rank of a tensor is the number of dimensions of the tensor

In [7]:
s1 = tf.Variable('It is done', tf.string)
s1.shape, tf.rank(s1)

(TensorShape([]), <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [8]:
x1 = tf.Variable(32, tf.int32)
x1.shape, tf.rank(x1)

(TensorShape([]), <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [9]:
x2 = tf.Variable([[1, 2, 3], [4, 5, 6]], tf.int32)
x2.shape, tf.rank(x2)

(TensorShape([2, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=2>)

##### Reshaping tensors

In [10]:
tf.reshape(x2, [3, 2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [11]:
tf.reshape(x2, [6, -1])  # -1 implies "infer the number of elements in this dimension"

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [12]:
tf.reshape(x2, [-1, 6])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

##### Constant and Variable tensors
  - You can point the constant tensor's name to another tensor
  - You cannot change the constant tensor's values inside, thus
    - it cannot be used during training
  - A variable tensor's values can be updated, thus
    - it can be used during training (default).
    - You can also create a variable tensor to be untrainable (using trainable=False)

In [18]:
c = tf.constant([[1, 8, 9]], tf.int32)
c = tf.constant([[1, 2, 3]], tf.int32)
c

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [19]:
d = tf.Variable([1, 8, 9], tf.int32)
d

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 8, 9], dtype=int32)>

In [20]:
d = 2 * d
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, 16, 18], dtype=int32)>